/run/numberOfThreads 4
/run/initialize

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 4.75 mm
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
/control/execute nspek.mac
/particle/createAllIon

/score/create/cylinderMesh Envelop1
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop2
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 13. 0. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop3
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 13. 13. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop4
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 26. 0. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop5
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 26. 13. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop6
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 26. 26. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop7
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 39. 0. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop8
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 39. 13. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop9
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 39. 26. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop10
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 39. 39. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop11
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 52. 0. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop12
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 52. 13. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop13
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 52. 26. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop14
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 52. 39. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close

/score/create/cylinderMesh Envelop15
/score/mesh/cylinderSize 7.5 50. mm
/score/mesh/nBin 15 100 1
/score/mesh/translate/xyz 52. 52. 0. mm 
/score/quantity/doseDeposit E
/score/quantity/doseDeposit pDep 
/score/filter/particle protonFilter proton
/score/quantity/doseDeposit eDep 
/score/filter/particle electronFilter e-
/score/quantity/doseDeposit oDep 
/score/filter/particle oFilter O16
/score/close





/gps/verbose 1

/run/beamOn 10000000

/score/dumpAllQuantitiesToFile Envelop1 n1.cvs
/score/dumpAllQuantitiesToFile Envelop2 n2.cvs
/score/dumpAllQuantitiesToFile Envelop3 n3.cvs
/score/dumpAllQuantitiesToFile Envelop4 n4.cvs
/score/dumpAllQuantitiesToFile Envelop5 n5.cvs
/score/dumpAllQuantitiesToFile Envelop6 n6.cvs
/score/dumpAllQuantitiesToFile Envelop7 n7.cvs
/score/dumpAllQuantitiesToFile Envelop8 n8.cvs
/score/dumpAllQuantitiesToFile Envelop9 n9.cvs
/score/dumpAllQuantitiesToFile Envelop10 n10.cvs
/score/dumpAllQuantitiesToFile Envelop11 n11.cvs
/score/dumpAllQuantitiesToFile Envelop12 n12.cvs
/score/dumpAllQuantitiesToFile Envelop13 n13.cvs
/score/dumpAllQuantitiesToFile Envelop14 n14.cvs
/score/dumpAllQuantitiesToFile Envelop15 n15.cvs
